name: Build "latest"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: oosterhuisf
          password: ${{ secrets.DOCKERHUB }}

      - name: Install qemu
        run: |
          sudo apt install qemu-user-static
          docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
          docker buildx create --name armbuilder
          docker buildx use armbuilder
          docker buildx inspect --bootstrap
          
      - name: Build and push docker images
        run: |          
          docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6 -t oosterhuisf/sbt:latest --push .
